# Generated by Django 5.0.6 on 2024-05-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
